[WIP] Add operator to Apollo
apolloconfig/apollo-operator pull request #1
Opened 2023-06-27 04:11 UTC by CSWYF3634076

What's the purpose of this PR
Add operator to Apollo

Which issue(s) this PR fixes:
Fixes https://github.com/apolloconfig/apollo/issues/4708

Finished content：portal&environment create delete update
Unfinished content： 1. allinone;  2.using secret instead of partial configmap;  3. log;  4. error handling;  5. code detail optimization

2023-06-27 05:42 UTC, JaredTan95 requested changes

2023-06-27 05:42 UTC, JaredTan95 commented on api/v1alpha1/apolloportal_types.go
> +	// TODO 后续看是否必要，不必则删除
all comments should be in English.

2023-06-27 05:42 UTC, JaredTan95 commented on pkg/reconcile/apollo/deleted.go
> +// DeleteConfigMaps 删除configmap
the same issue, should be in English

2023-06-27 05:42 UTC, JaredTan95 commented on controllers/apolloenvironment_controller.go
> +	log.Info("进入ApolloPortalReconciler Reconcile")
all logs should be in English

2023-06-27 07:16 UTC, JaredTan95 requested changes

2023-06-27 07:16 UTC, JaredTan95 commented on go.mod
> +module apollo.io/apollo-operator
how about keeping it same with Apollo config domain `www.apolloconfig.com`, e.g. `module apolloconfig.com/apollo-operator`

2023-09-10 13:42 UTC, JaredTan95 requested changes

2023-09-10 13:42 UTC, JaredTan95 commented on controllers/apolloenvironment_controller.go
> +		Owns(&appsv1.StatefulSet{}).
Do we need to watch daemonset and statefulset?

2023-09-10 13:42 UTC, JaredTan95 commented on controllers/apolloportal_controller.go
> +		Owns(&appsv1.StatefulSet{}).
the same issue here.

2023-09-10 13:43 UTC, JaredTan95 commented
>  manager E0910 13:42:13.325747       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1.Ingress: failed to list *v1.Ingress
│ : ingresses.networking.k8s.io is forbidden: User "system:serviceaccount:apollo-operator-system:apollo-operator-controller-manager" cannot list resource "ingresses" in API gro
│ up "networking.k8s.io" at the cluster scope

need to check the permission issue.

2023-09-18 06:47 UTC, CSWYF3634076 commented
> > manager E0910 13:42:13.325747       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1.Ingress: failed to list *v1.Ingress
> > │ : ingresses.networking.k8s.io is forbidden: User "system:serviceaccount:apollo-operator-system:apollo-operator-controller-manager" cannot list resource "ingresses" in API gro
> > │ up "networking.k8s.io" at the cluster scope
> 
> need to check the permission issue.

done

2023-10-01 13:54 UTC, JaredTan95 approved these changes
Thank you for your persistence and contribution in contributing such a wonderful component and feature to the apollo community, which makes apollo more possible in the cloud native scenario.

2023-10-01 13:54 UTC, merged

2023-10-05 08:15 UTC, nobodyiam commented
Fantastic work! Should we incorporate guidance on configuring the new Apollo CR within the [README.md](https://github.com/apolloconfig/apollo-operator/blob/main/README.md) file?

2023-10-05 13:51 UTC, JaredTan95 commented
> Fantastic work! Should we incorporate guidance on configuring the new Apollo CR within the [README.md](https://github.com/apolloconfig/apollo-operator/blob/main/README.md) file?

yes,it will be added in following PRs.

2023-10-05 13:56 UTC, CSWYF3634076 commented
> Fantastic work! Should we incorporate guidance on configuring the new Apollo CR within the [README.md](https://github.com/apolloconfig/apollo-operator/blob/main/README.md) file?

Yes, I will add explanations for each field in yaml later